/*
 * File: pass_primitive.c
 *
 * MATLAB Coder version            : 5.2
 * C/C++ source code generated on  : 03-Dec-2022 14:11:43
 */

/* Include Files */
#include "pass_primitive.h"
#include "primitives_rtwutil.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Definitions */
/*
 * Arguments    : double v0
 *                double a0
 *                double sf
 *                double vfmin
 *                double vfmax
 *                double Tmin
 *                double Tmax
 *                double coeffsT2[6]
 *                double *v2
 *                double *T2
 *                double coeffsT1[6]
 *                double *v1
 *                double *T1
 * Return Type  : void
 */
void pass_primitive(double v0, double a0, double sf, double vfmin, double vfmax,
                    double Tmin, double Tmax, double coeffsT2[6], double *v2,
                    double *T2, double coeffsT1[6], double *v1, double *T1)
{
  double Tstar;
  double Tvmax;
  double b_v2_tmp;
  double c_v2_tmp;
  double coeffsT1_tmp;
  double t3;
  double t4;
  double v2_tmp;
  double vfminStar;
  int i;
  /*  */
  /*            Agent Logic */
  /*          Pass Primitive */
  /*               2022 */
  /*  */
  /*  */
  /*  */
  if (a0 >= 0.0) {
    /* FINAL_OPT_TIME_PASS */
    /*     OUT1 = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:12 */
    vfminStar = a0 * sf * 60.0;
    Tstar = v0 * v0 * 49.0;
    Tvmax = sf * 30.0 /
            ((v0 * 7.0 + vfmax * 8.0) +
             sqrt(((vfminStar + v0 * vfmax * 112.0) + Tstar) +
                  vfmax * vfmax * 64.0));
    /* FINAL_OPT_TIME_PASS */
    /*     OUT1 = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:12 */
    Tstar = sf * 30.0 /
            ((v0 * 7.0 + vfmin * 8.0) +
             sqrt(((vfminStar + v0 * vfmin * 112.0) + Tstar) +
                  vfmin * vfmin * 64.0));
  } else {
    /* TIME_MIN_VEL */
    /*     OUT1 = TIME_MIN_VEL(A0,SF) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:12 */
    Tstar = -(3.872983346207417 * sqrt(-a0 * sf)) / a0;
    /* FINAL_OPT_VEL_PASS */
    /*     FINAL_OPT_VEL_PASS_VAR = FINAL_OPT_VEL_PASS(V0,A0,SF,T) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:12 */
    vfminStar =
        ((sf * -15.0 + Tstar * v0 * 7.0) + Tstar * Tstar * a0) * -0.125 / Tstar;
    if ((vfminStar < vfmin) && (vfminStar < vfmax)) {
      /* FINAL_OPT_TIME_PASS */
      /*     OUT1 = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 8.7. */
      /*     03-Dec-2022 13:54:12 */
      Tvmax = sf * 30.0 /
              ((v0 * 7.0 + vfmax * 8.0) +
               sqrt(((a0 * sf * 60.0 + v0 * vfmax * 112.0) + v0 * v0 * 49.0) +
                    vfmax * vfmax * 64.0));
      /* FINAL_OPT_TIME_PASS */
      /*     OUT1 = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 8.7. */
      /*     03-Dec-2022 13:54:12 */
      Tstar = sf * 30.0 /
              ((v0 * 7.0 + vfmin * 8.0) +
               sqrt(((a0 * sf * 60.0 + v0 * vfmin * 112.0) + v0 * v0 * 49.0) +
                    vfmin * vfmin * 64.0));
    } else if ((vfmin < vfminStar) && (vfminStar < vfmax)) {
      /* FINAL_OPT_TIME_PASS */
      /*     OUT1 = FINAL_OPT_TIME_PASS(V0,A0,SF,VF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 8.7. */
      /*     03-Dec-2022 13:54:12 */
      Tvmax = sf * 30.0 /
              ((v0 * 7.0 + vfmax * 8.0) +
               sqrt(((a0 * sf * 60.0 + v0 * vfmax * 112.0) + v0 * v0 * 49.0) +
                    vfmax * vfmax * 64.0));
    } else {
      Tvmax = 0.0;
      Tstar = 0.0;
    }
  }
  if ((Tmin == 0.0) && (Tmax == 0.0)) {
    *T1 = Tvmax;
    *T2 = Tstar;
  } else {
    *T1 = fmax(Tvmax, Tmin);
    *T2 = fmin(Tstar, Tmax);
  }
  if ((Tvmax != 0.0) && (Tvmax <= Tstar) && (*T1 <= *T2)) {
    /* FINAL_OPT_VEL_PASS */
    /*     FINAL_OPT_VEL_PASS_VAR = FINAL_OPT_VEL_PASS(V0,A0,SF,T) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:12 */
    vfminStar = *T1 * *T1;
    Tstar = *T1 * v0;
    Tvmax = vfminStar * a0;
    *v1 = ((sf * -15.0 + Tstar * 7.0) + Tvmax) * -0.125 / *T1;
    /* FINAL_OPT_VEL_PASS */
    /*     FINAL_OPT_VEL_PASS_VAR = FINAL_OPT_VEL_PASS(V0,A0,SF,T) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:12 */
    v2_tmp = *T2 * *T2;
    b_v2_tmp = *T2 * v0;
    c_v2_tmp = v2_tmp * a0;
    *v2 = ((sf * -15.0 + b_v2_tmp * 7.0) + c_v2_tmp) * -0.125 / *T2;
    /* COEF_LIST */
    /*     COEF_LIST_VAR = COEF_LIST(V0,A0,SF,VF,AF,T) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:11 */
    t3 = 0.0 * vfminStar;
    t4 = Tvmax * 3.0;
    coeffsT1[0] = 0.0;
    coeffsT1[1] = v0;
    coeffsT1[2] = a0;
    coeffsT1_tmp = *T1 * *v1;
    coeffsT1[3] =
        1.0 / rt_powd_snf(*T1, 3.0) *
        ((((sf * -20.0 + t4) + -t3) + Tstar * 12.0) + coeffsT1_tmp * 8.0) *
        -3.0;
    coeffsT1[4] = 1.0 / (vfminStar * vfminStar) *
                  ((((sf * -30.0 - t3 * 2.0) + t4) + Tstar * 16.0) +
                   coeffsT1_tmp * 14.0) *
                  12.0;
    coeffsT1[5] =
        1.0 / rt_powd_snf(*T1, 5.0) *
        ((((sf * -12.0 + -t3) + Tstar * 6.0) + coeffsT1_tmp * 6.0) + Tvmax) *
        -60.0;
    /* COEF_LIST */
    /*     COEF_LIST_VAR = COEF_LIST(V0,A0,SF,VF,AF,T) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:11 */
    t3 = 0.0 * v2_tmp;
    t4 = c_v2_tmp * 3.0;
    coeffsT2[0] = 0.0;
    coeffsT2[1] = v0;
    coeffsT2[2] = a0;
    vfminStar = *T2 * *v2;
    coeffsT2[3] =
        1.0 / rt_powd_snf(*T2, 3.0) *
        ((((sf * -20.0 + t4) + -t3) + b_v2_tmp * 12.0) + vfminStar * 8.0) *
        -3.0;
    coeffsT2[4] = 1.0 / (v2_tmp * v2_tmp) *
                  ((((sf * -30.0 - t3 * 2.0) + t4) + b_v2_tmp * 16.0) +
                   vfminStar * 14.0) *
                  12.0;
    coeffsT2[5] =
        1.0 / rt_powd_snf(*T2, 5.0) *
        ((((sf * -12.0 + -t3) + b_v2_tmp * 6.0) + vfminStar * 6.0) + c_v2_tmp) *
        -60.0;
  } else {
    for (i = 0; i < 6; i++) {
      coeffsT1[i] = 0.0;
      coeffsT2[i] = 0.0;
    }
    *T1 = 0.0;
    *T2 = 0.0;
    *v1 = 0.0;
    *v2 = 0.0;
  }
}

/*
 * File trailer for pass_primitive.c
 *
 * [EOF]
 */
