/*
 * File: pass_primitive_j0.c
 *
 * MATLAB Coder version            : 5.2
 * C/C++ source code generated on  : 03-Dec-2022 14:11:43
 */

/* Include Files */
#include "pass_primitive_j0.h"
#include "primitives_rtwutil.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Definitions */
/*
 * Arguments    : double v0
 *                double a0
 *                double sf
 *                double vfmin
 *                double vfmax
 *                double coefsj0[6]
 *                double *vfj0
 *                double *tfj0
 * Return Type  : void
 */
void pass_primitive_j0(double v0, double a0, double sf, double vfmin,
                       double vfmax, double coefsj0[6], double *vfj0,
                       double *tfj0)
{
  double b_vfj0_tmp;
  double c_vfj0_tmp;
  double coefsj0_tmp;
  double t2;
  double t3;
  double t4;
  double t9;
  double tfj0_list_idx_0;
  double vfj0_tmp;
  int i;
  /*  */
  /*           Agent Logic */
  /*          Pass Primitive */
  /*               2022 */
  /*  */
  /*  */
  /*  */
  /* FINAL_OPT_TIME_J0_PASS */
  /*     FINAL_OPT_TIME_J0_PASS_VAR = FINAL_OPT_TIME_J0_PASS(V0,A0,SF) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.7.
   */
  /*     03-Dec-2022 13:54:13 */
  t2 = v0 * 5.0;
  t9 = 2.23606797749979 * sqrt(a0 * sf * 8.0 + t2 * v0);
  tfj0_list_idx_0 = sf * 10.0 / (t2 + t9);
  *tfj0 = sf * 10.0 / (t2 - t9);
  /* FINAL_OPT_VEL_J0_PASS */
  /*     FINAL_OPT_VEL_J0_PASS_VAR = FINAL_OPT_VEL_J0_PASS(V0,A0,J0,SF,AF,T) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.7.
   */
  /*     03-Dec-2022 13:54:13 */
  t2 = tfj0_list_idx_0 * tfj0_list_idx_0;
  t9 = tfj0_list_idx_0 * v0;
  vfj0_tmp = t9 * 12.0;
  b_vfj0_tmp = 1.0 / rt_powd_snf(tfj0_list_idx_0, 3.0);
  c_vfj0_tmp = a0 * t2;
  *vfj0 = t2 *
          (0.0 - b_vfj0_tmp *
                     (((sf * 20.0 - vfj0_tmp) - c_vfj0_tmp * 3.0) + 0.0 * t2) *
                     3.0) *
          -0.041666666666666664;
  if ((vfmin < *vfj0) && (vfmax > *vfj0)) {
    *tfj0 = tfj0_list_idx_0;
    /* COEF_LIST */
    /*     COEF_LIST_VAR = COEF_LIST(V0,A0,SF,VF,AF,T) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:11 */
    t3 = 0.0 * t2;
    t4 = c_vfj0_tmp * 3.0;
    coefsj0[0] = 0.0;
    coefsj0[1] = v0;
    coefsj0[2] = a0;
    coefsj0_tmp = tfj0_list_idx_0 * *vfj0;
    coefsj0[3] = b_vfj0_tmp *
                 ((((sf * -20.0 + t4) + -t3) + vfj0_tmp) + coefsj0_tmp * 8.0) *
                 -3.0;
    coefsj0[4] =
        1.0 / (t2 * t2) *
        ((((sf * -30.0 - t3 * 2.0) + t4) + t9 * 16.0) + coefsj0_tmp * 14.0) *
        12.0;
    coefsj0[5] =
        1.0 / rt_powd_snf(tfj0_list_idx_0, 5.0) *
        ((((sf * -12.0 + -t3) + t9 * 6.0) + coefsj0_tmp * 6.0) + c_vfj0_tmp) *
        -60.0;
  } else {
    /* FINAL_OPT_VEL_J0_PASS */
    /*     FINAL_OPT_VEL_J0_PASS_VAR = FINAL_OPT_VEL_J0_PASS(V0,A0,J0,SF,AF,T)
     */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:13 */
    t2 = *tfj0 * *tfj0;
    t9 = *tfj0 * v0;
    vfj0_tmp = t9 * 12.0;
    b_vfj0_tmp = 1.0 / rt_powd_snf(*tfj0, 3.0);
    c_vfj0_tmp = a0 * t2;
    *vfj0 =
        t2 *
        (0.0 - b_vfj0_tmp *
                   (((sf * 20.0 - vfj0_tmp) - c_vfj0_tmp * 3.0) + 0.0 * t2) *
                   3.0) *
        -0.041666666666666664;
    if ((vfmin < *vfj0) && (vfmax > *vfj0)) {
      /* COEF_LIST */
      /*     COEF_LIST_VAR = COEF_LIST(V0,A0,SF,VF,AF,T) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 8.7. */
      /*     03-Dec-2022 13:54:11 */
      t3 = 0.0 * t2;
      t4 = c_vfj0_tmp * 3.0;
      coefsj0[0] = 0.0;
      coefsj0[1] = v0;
      coefsj0[2] = a0;
      coefsj0_tmp = *tfj0 * *vfj0;
      coefsj0[3] =
          b_vfj0_tmp *
          ((((sf * -20.0 + t4) + -t3) + vfj0_tmp) + coefsj0_tmp * 8.0) * -3.0;
      coefsj0[4] =
          1.0 / (t2 * t2) *
          ((((sf * -30.0 - t3 * 2.0) + t4) + t9 * 16.0) + coefsj0_tmp * 14.0) *
          12.0;
      coefsj0[5] =
          1.0 / rt_powd_snf(*tfj0, 5.0) *
          ((((sf * -12.0 + -t3) + t9 * 6.0) + coefsj0_tmp * 6.0) + c_vfj0_tmp) *
          -60.0;
    } else {
      for (i = 0; i < 6; i++) {
        coefsj0[i] = 0.0;
      }
      *tfj0 = 0.0;
      *vfj0 = 0.0;
    }
  }
}

/*
 * File trailer for pass_primitive_j0.c
 *
 * [EOF]
 */
