/*
 * File: stop_primitive.c
 *
 * MATLAB Coder version            : 5.2
 * C/C++ source code generated on  : 03-Dec-2022 14:11:43
 */

/* Include Files */
#include "stop_primitive.h"
#include "primitives_rtwutil.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Definitions */
/*
 * Arguments    : double v0
 *                double a0
 *                double sf
 *                double coefs[6]
 *                double *maxsf
 *                double *tf
 * Return Type  : void
 */
void stop_primitive(double v0, double a0, double sf, double coefs[6],
                    double *maxsf, double *tf)
{
  double coefs_tmp;
  double t2;
  double t3;
  double t4;
  double t4_tmp;
  int i;
  /*  */
  /*           Agent Logic */
  /*          Stop Primitive */
  /*               2022 */
  /*  */
  /*  */
  /*  */
  if (v0 > 0.0) {
    *maxsf = sf;
    t2 = 4.0 * (v0 * v0);
    if (t2 + 5.0 * a0 * sf < 0.0) {
      *maxsf = -(t2 / (5.0 * a0));
      *tf = 5.0 * *maxsf / v0;
    } else {
      /* FINAL_OPT_TIME_STOP */
      /*     OUT1 = FINAL_OPT_TIME_STOP(V0,A0,SF) */
      /*     This function was generated by the Symbolic Math Toolbox
       * version 8.7. */
      /*     03-Dec-2022 13:54:12 */
      *tf = sf * 10.0 / (v0 * 2.0 + sqrt(a0 * sf * 5.0 + t2));
    }
    /* COEF_LIST */
    /*     COEF_LIST_VAR = COEF_LIST(V0,A0,SF,VF,AF,T) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:11 */
    t2 = *tf * *tf;
    t3 = 0.0 * t2;
    t4_tmp = a0 * t2;
    t4 = t4_tmp * 3.0;
    coefs[0] = 0.0;
    coefs[1] = v0;
    coefs[2] = a0;
    coefs_tmp = *tf * v0;
    coefs[3] =
        1.0 / rt_powd_snf(*tf, 3.0) *
        ((((*maxsf * -20.0 + t4) + -t3) + coefs_tmp * 12.0) + *tf * 0.0 * 8.0) *
        -3.0;
    coefs[4] = 1.0 / (t2 * t2) *
               ((((*maxsf * -30.0 - t3 * 2.0) + t4) + coefs_tmp * 16.0) +
                *tf * 0.0 * 14.0) *
               12.0;
    coefs[5] = 1.0 / rt_powd_snf(*tf, 5.0) *
               ((((*maxsf * -12.0 + -t3) + coefs_tmp * 6.0) + *tf * 0.0 * 6.0) +
                t4_tmp) *
               -60.0;
  } else {
    *maxsf = 0.0;
    *tf = 0.0;
    for (i = 0; i < 6; i++) {
      coefs[i] = 0.0;
    }
  }
}

/*
 * File trailer for stop_primitive.c
 *
 * [EOF]
 */
