/*
 * File: stop_primitive_j0.c
 *
 * MATLAB Coder version            : 5.2
 * C/C++ source code generated on  : 03-Dec-2022 14:11:43
 */

/* Include Files */
#include "stop_primitive_j0.h"
#include "primitives_rtwutil.h"
#include "rt_nonfinite.h"

/* Function Definitions */
/*
 * Arguments    : double v0
 *                double a0
 *                double coefsj0[6]
 *                double *sfj0
 *                double *tfj0
 * Return Type  : void
 */
void stop_primitive_j0(double v0, double a0, double coefsj0[6], double *sfj0,
                       double *tfj0)
{
  double b_sfj0_tmp;
  double c_sfj0_tmp;
  double d_sfj0_tmp;
  double sfj0_tmp;
  double sfj0_tmp_tmp;
  double t2_tmp;
  double t3;
  double t4;
  int i;
  /*  */
  /*            Agent Logic */
  /*          Stop Primitive */
  /*               2022 */
  /*  */
  /*  */
  /*  */
  if ((v0 > 0.0) && (a0 < 0.0)) {
    /* FINAL_OPT_TIME_STOP_J0 */
    /*     OUT1 = FINAL_OPT_TIME_STOP_J0(V0,A0) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:13 */
    *tfj0 = v0 * -2.0 / a0;
    /* FINAL_OPT_POS_J0 */
    /*     FINAL_OPT_POS_J0_VAR = FINAL_OPT_POS_J0(V0,A0,J0,VF,AF,T) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:12 */
    t2_tmp = *tfj0 * *tfj0;
    t3 = rt_powd_snf(*tfj0, 3.0);
    sfj0_tmp_tmp = *tfj0 * v0;
    sfj0_tmp = sfj0_tmp_tmp * 12.0;
    b_sfj0_tmp = *tfj0 * 0.0 * 8.0;
    c_sfj0_tmp = 1.0 / t3;
    d_sfj0_tmp = a0 * t2_tmp;
    *sfj0 =
        t3 *
        (c_sfj0_tmp *
         (((sfj0_tmp + b_sfj0_tmp) + d_sfj0_tmp * 3.0) - 0.0 * t2_tmp) * 3.0) /
        60.0;
    /* COEF_LIST */
    /*     COEF_LIST_VAR = COEF_LIST(V0,A0,SF,VF,AF,T) */
    /*     This function was generated by the Symbolic Math Toolbox version 8.7.
     */
    /*     03-Dec-2022 13:54:11 */
    t3 = 0.0 * t2_tmp;
    t4 = d_sfj0_tmp * 3.0;
    coefsj0[0] = 0.0;
    coefsj0[1] = v0;
    coefsj0[2] = a0;
    coefsj0[3] = c_sfj0_tmp *
                 ((((*sfj0 * -20.0 + t4) + -t3) + sfj0_tmp) + b_sfj0_tmp) *
                 -3.0;
    coefsj0[4] = 1.0 / (t2_tmp * t2_tmp) *
                 ((((*sfj0 * -30.0 - t3 * 2.0) + t4) + sfj0_tmp_tmp * 16.0) +
                  *tfj0 * 0.0 * 14.0) *
                 12.0;
    coefsj0[5] =
        1.0 / rt_powd_snf(*tfj0, 5.0) *
        ((((*sfj0 * -12.0 + -t3) + sfj0_tmp_tmp * 6.0) + *tfj0 * 0.0 * 6.0) +
         d_sfj0_tmp) *
        -60.0;
  } else {
    *sfj0 = 0.0;
    *tfj0 = 0.0;
    for (i = 0; i < 6; i++) {
      coefsj0[i] = 0.0;
    }
  }
}

/*
 * File trailer for stop_primitive_j0.c
 *
 * [EOF]
 */
